/**
 * Default Questionnaire Templates
 * 
 * Pre-built SurveyJS JSON templates for weekly questionnaires (Weeks 1-5)
 */

export const DEFAULT_TEMPLATES = {
  week1: {
    title: "Week 1 Check-In",
    description: "Tell us how your first week went!",
    pages: [
      {
        name: "week1",
        elements: [
          {
            type: "comment",
            name: "wins",
            title: "What were your biggest wins this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "challenges",
            title: "What challenges did you face?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "nutrition_help",
            title: "What area of nutrition do you need the most help with?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "behavior_goals",
            title: "What specific behavior goals will you focus on this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "text",
            name: "days_trained",
            title: "How many days did you train this week?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_hit_target",
            title: "How many days did you hit your protein target?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_on_calories",
            title: "How many days were you on track with calories?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
        ],
      },
    ],
  },
  week2: {
    title: "Week 2 Check-In",
    description: "Let's check in on your progress!",
    pages: [
      {
        name: "week2",
        elements: [
          {
            type: "comment",
            name: "last_week_goal_review",
            title: "How did last week's behavior goals go?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "wins",
            title: "What were your biggest wins this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "challenges",
            title: "What challenges did you face?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "nutrition_help",
            title: "What area of nutrition do you need the most help with?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "behavior_goals",
            title: "What specific behavior goals will you focus on this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "text",
            name: "days_trained",
            title: "How many days did you train this week?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_hit_target",
            title: "How many days did you hit your protein target?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_on_calories",
            title: "How many days were you on track with calories?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
        ],
      },
    ],
  },
  week3: {
    title: "Week 3 Check-In",
    description: "Halfway through - let's keep the momentum going!",
    pages: [
      {
        name: "week3",
        elements: [
          {
            type: "comment",
            name: "last_week_goal_review",
            title: "How did last week's behavior goals go?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "wins",
            title: "What were your biggest wins this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "challenges",
            title: "What challenges did you face?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "nutrition_help",
            title: "What area of nutrition do you need the most help with?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "behavior_goals",
            title: "What specific behavior goals will you focus on this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "text",
            name: "days_trained",
            title: "How many days did you train this week?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_hit_target",
            title: "How many days did you hit your protein target?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_on_calories",
            title: "How many days were you on track with calories?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
        ],
      },
    ],
  },
  week4: {
    title: "Week 4 Check-In",
    description: "One month in - time to reflect!",
    pages: [
      {
        name: "week4",
        elements: [
          {
            type: "comment",
            name: "last_week_goal_review",
            title: "How did last week's behavior goals go?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "monthly_pride",
            title: "What are you most proud of this month?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "wins",
            title: "What were your biggest wins this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "challenges",
            title: "What challenges did you face?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "nutrition_help",
            title: "What area of nutrition do you need the most help with?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "behavior_goals",
            title: "What specific behavior goals will you focus on this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "text",
            name: "days_trained",
            title: "How many days did you train this week?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_hit_target",
            title: "How many days did you hit your protein target?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_on_calories",
            title: "How many days were you on track with calories?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
        ],
      },
    ],
  },
  week5: {
    title: "Week 5 Check-In",
    description: "Final stretch - let's finish strong!",
    pages: [
      {
        name: "week5",
        elements: [
          {
            type: "comment",
            name: "last_week_goal_review",
            title: "How did last week's behavior goals go?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "wins",
            title: "What were your biggest wins this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "challenges",
            title: "What challenges did you face?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "nutrition_help",
            title: "What area of nutrition do you need the most help with?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "comment",
            name: "behavior_goals",
            title: "What specific behavior goals will you focus on this week?",
            isRequired: true,
            rows: 3,
          },
          {
            type: "text",
            name: "days_trained",
            title: "How many days did you train this week?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_hit_target",
            title: "How many days did you hit your protein target?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
          {
            type: "text",
            name: "days_on_calories",
            title: "How many days were you on track with calories?",
            inputType: "number",
            min: 0,
            max: 7,
            isRequired: true,
          },
        ],
      },
    ],
  },
}

export type TemplateKey = keyof typeof DEFAULT_TEMPLATES
