-- AlterTable
ALTER TABLE "Entry" ADD COLUMN "proteinGrams" DOUBLE PRECISION;
ALTER TABLE "Entry" ADD COLUMN "carbsGrams" DOUBLE PRECISION;
ALTER TABLE "Entry" ADD COLUMN "fatGrams" DOUBLE PRECISION;
ALTER TABLE "Entry" ADD COLUMN "fiberGrams" DOUBLE PRECISION;
